export const CITY_OPTIONS = [
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Utara",
  "Bogor",
  "Depok",
  "Tangerang",
  "Tangerang Selatan",
  "Bekasi",
  "Cikarang",
  "Bandung",
  "Cimahi",
  "Semarang",
  "Yogyakarta",
  "Surakarta",
  "Surabaya",
  "Malang",
  "Sidoarjo",
  "Denpasar",
  "Medan",
  "Pekanbaru",
  "Palembang",
  "Batam",
  "Makassar",
  "Manado",
  "Balikpapan",
  "Samarinda",
  "Banjarmasin",
] as const;

export const INDUSTRY_OPTIONS = [
  "Logistik",
  "Manufaktur",
  "Ritel",
  "F&B",
  "Telekomunikasi",
  "Teknologi Informasi",
  "Jasa Keuangan",
  "Perbankan",
  "Asuransi",
  "Kesehatan",
  "Pendidikan",
  "Konstruksi",
  "Properti",
  "Energi",
  "Pertambangan",
  "Pertanian",
  "Otomotif",
  "Media & Kreatif",
  "Pariwisata & Perhotelan",
  "Transportasi",
  "Pemerintahan",
  "NGO",
] as const;

