export const CITY_OPTIONS = [
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Utara",
  "Bogor",
  "Depok",
  "Tangerang",
  "Tangerang Selatan",
  "Bekasi",
  "Cikarang",
  "Bandung",
  "Cimahi",
  "Semarang",
  "Yogyakarta",
  "Surakarta",
  "Surabaya",
  "Malang",
  "Sidoarjo",
  "Denpasar",
  "Medan",
  "Pekanbaru",
  "Palembang",
  "Batam",
  "Makassar",
  "Manado",
  "Balikpapan",
  "Samarinda",
  "Banjarmasin",
] as const;

export const INDUSTRY_OPTIONS = [
  "Layanan Profesional",
  "Marketing",
  "Sales & Bisnis",
  "Akuntansi & Keuangan",
  "Ritel",
  "Logistik & Pergudangan",
  "Administrasi & HR",
  "Pendidikan",
  "Media & Kreatif",
  "Customer Service",
  "Operasional",
  "Teknisi & Produksi",
  "Properti & Konstruksi",
  "Kesehatan",
  "Teknologi Informasi",
  "Hotel & Pariwisata",
] as const;

