export const INDUSTRY_OPTIONS = [
  "Layanan Profesional",
  "Marketing",
  "Sales & Bisnis",
  "Akuntansi & Keuangan",
  "Ritel",
  "Logistik & Pergudangan",
  "Administrasi & HR",
  "Pendidikan",
  "Media & Kreatif",
  "Customer Service",
  "Operasional",
  "Teknisi & Produksi",
  "Properti & Konstruksi",
  "Kesehatan",
  "Teknologi Informasi",
  "Hotel & Pariwisata",
] as const;
